AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Gemspec/RequireMFA: 
  Enabled: false
